### ISSUE TITLE
Install instructions fail for go v15.

### ISSUE THREAD

**Issue by ErikEvenson** [IBM/packer-plugin-ibmcloud#15]
I get the following error when using the `README.md` install instructions:

```
% go build
builder/ibmcloud/builder.go:11:3: cannot find package "github.com/hashicorp/hcl/v2/hcldec" in any of:
	/usr/local/Cellar/go/1.15/libexec/src/github.com/hashicorp/hcl/v2/hcldec (from $GOROOT)
	/Users/eevenson/Documents/Projects/go/src/github.com/hashicorp/hcl/v2/hcldec (from $GOPATH)
eevenson@qengho packer-builder-ibmcloud % go version
go version go1.15 darwin/amd64
```

I believe this has to do with the $GOPATH vs $GO111MODULE thing (https://dev.to/maelvls/why-is-go111module-everywhere-and-everything-about-go-modules-24k).

**Comment by juanpinzon** [comment]
ErikEvenson if your OS is Ubuntu you can use the script https://github.com/IBM/packer-plugin-ibmcloud/tree/master/vsi-linux-setup, to setup your machine. Otherwise you can follow the steps on the script to install the dependencies required by Packer HCL2

**Comment by ErikEvenson** [comment]
I'm on Darwin architecture.  I installed the dependencies listed.

**Comment by juanpinzon** [comment]
Please install the dependencies on the script Steps 5-7, the README.md is not updated.

**Comment by ErikEvenson** [comment]
Thanks.  I got this to work by tweaking the script.  I'll see if I can submit a pull request to update the README.md a bit.
