### ISSUE TITLE
While running the go build getting error

### ISSUE THREAD

**Issue by vknemanavar** [IBM/packer-plugin-ibmcloud#16]
While running the go build getting below error
# github.com/ibmcloud/packer-builder-ibmcloud/builder/ibmcloud
builder/ibmcloud/builder.go:68:48: cannot use self.config.KeyValueFilter.FlatMapstructure().HCL2Spec() (type map[string]"github.com/hashicorp/packer/vendor/github.com/hashicorp/hcl/v2/hcldec".Spec) as type "github.com/hashicorp/hcl/v2/hcldec".ObjectSpec in return argument

**Comment by juanpinzon** [comment]
vknemanavar  if your OS is Ubuntu you can use the script https://github.com/IBM/packer-plugin-ibmcloud/tree/master/vsi-linux-setup, to setup your machine. Otherwise you can follow the steps on the script to install the dependencies required by Packer HCL2. Please install the dependencies on the script Steps 5-7, the README.md is not updated.

**Comment by vknemanavar** [comment]
In Ubuntu OS getting below error. Is there possible to get directly plugin binary to use it in packer?

import cycle not allowed
package github.com/ibmcloud/packer-builder-ibmcloud
	imports github.com/ibmcloud/packer-builder-ibmcloud/builder/ibmcloud
	imports github.com/hashicorp/packer/hcl2template
	imports github.com/hashicorp/hcl/v2/ext/typeexpr
	imports github.com/hashicorp/hcl/v2/hclsyntax
	imports github.com/zclconf/go-cty/cty/function/stdlib
	imports github.com/apparentlymart/go-textseg/v12/textseg
	imports github.com/apparentlymart/go-textseg/v12/textseg

**Comment by juanpinzon** [comment]
I am not able to reproduce your error. Could you please run setup.sh script , you will be fine after running it.

**Comment by vknemanavar** [comment]
I was able to fix the issue, default it is connecting to vsi using public IP can we change it to private IP?

**Comment by juanpinzon** [comment]
@Nitinhuralikuppi
