### ISSUE TITLE
VPC compatible images

### ISSUE THREAD

**Issue by drjeep** [IBM/packer-plugin-ibmcloud#24]
Are there any plans for this plugin to support building VPC compatible images? Currently the only way to create these is to manually create, convert and upload images to Cloud Object Storage as documented here

https://cloud.ibm.com/docs/vpc?topic=vpc-managing-images

**Comment by juanpinzon** [comment]
Hi @drjeep Yes, the packer plugin for VPC is in developing stage right now.
