### ISSUE TITLE
Proper GH release for packer plugin

### ISSUE THREAD

**Issue by guillermo-menjivar** [IBM/packer-plugin-ibmcloud#25]
Thank you for this project, we are starting to use this plugin. You share several different ways to build this plugin. I think it will be easier if in addition to the instructions you provider a release binary of each respective architecture, reducing the need to determine which build process to use.
This is a common pattern around packer plugins. Ex: https://github.com/vultr/packer-builder-vultr/tags

**Comment by juanpinzon** [comment]
Hi @guillermo-menjivar thank you so much for your comment and your suggestion. I will take care of them and update the repository as soon as I made the changes.

**Comment by juanpinzon** [comment]
Hi @guillermo-menjivar  you can find the binaries here https://github.com/IBM/packer-plugin-ibmcloud/releases/tag/v1.0.1
