### ISSUE TITLE
Gen2 support

### ISSUE THREAD

**Issue by tehlers320** [IBM/packer-plugin-ibmcloud#33]
How do you send the build to a specific resource group?

**Comment by Nitinhuralikuppi** [comment]
Plugin is developed for IBM Cloud Classic infrastructure. Classic does not have resource group concept.

**Comment by tehlers320** [comment]
@Nitinhuralikuppi  is gen2 supported elsewhere or will this have an update in the future?

**Comment by Nitinhuralikuppi** [comment]
Snapshot feature is not yet available on gen2 to build one. Will update the plugin once we have APIs available on gen2

**Comment by tehlers320** [comment]
Is snapshot available on gen2?

**Comment by tehlers320** [comment]
Will there be another plugin?
