### ISSUE TITLE
Support for Linux OS

### ISSUE THREAD

**Issue by jowko** [IBM/packer-plugin-ibmcloud#35]
I tried to use hcl examples on Windows and Ubuntu, but it looks like these platforms are either not supported or they not work properly.
So this command:
`packer init -upgrade examples/build.vpc.centos-ansible.pkr.hcl`
Gives me such errors (different errors are from different tools and VPN settings):
`could not find a local nor a remote checksum for plugin "github.com/ibm/ibmcloud" ">=v2.0.1"`
`no release version found for the github.com/ibm/ibmcloud plugin matching the constraint(s): ">=v2.0.1"`
I also wanted to install it manually, but I see that there are only macOS binaries.

Are other OS supported? If no, @juanpinzon do you know when support for them will be introduced?

**Comment by juanpinzon** [comment]
Hi @jowko you are correct there is no binaries at this point for Linux nor Windows OS. The only one available is on macOS. I think at the end of this week (August 13) I will introduce the binaries for Linux and Windows.
If you need such OS sooner you can use https://github.com/IBM/packer-plugin-ibmcloud#automation-via-docker-container or https://github.com/IBM/packer-plugin-ibmcloud#manual-installation to get the binary for Linux. For Windows you need to setup a Windows machine and follow https://github.com/IBM/packer-plugin-ibmcloud#manual-installation

**Comment by juanpinzon** [comment]
Check release v2.0.1

**Comment by jowko** [comment]
I managed to install this plugin on linux using packer init command.
It didn't worked on Windows (used both git bash and powershell).
I tried to copy binaries manually to `%APPDATA%\packer.d\plugins\github.com\ibm\ibmcloud` but it didn't work even after I commented `required_plugins` section. On packer validate such message is shown: `Error: Unknown source type ibmcloud-vpc`
