### ISSUE TITLE
Error on CentOS examples build: interface conversion: interface {} is nil, not string

### ISSUE THREAD

**Issue by jowko** [IBM/packer-plugin-ibmcloud#36]
Environment:
Windows 10 Pro 19042 & Git bash 2.29.2.windows.1
Run commands via makefile with the usage of [docker image](https://github.com/IBM/packer-plugin-ibmcloud#automation-via-docker-container).

I run examples: `build.vpc.centos.pkr.hcl` and `build.vpc.centos-ansible.pkr.hcl`. I adjusted `region`, `subnet_id`, `resource_group_id`, `vsi_base_image_id` (`r010-6f153a5d-6a9a-496d-8063-5c39932f6ded` which is `ibm-centos-7-6-minimal-amd64-2`, but the same error is on default image). I left default empty `security_group_id`.

When packer started, VM instance was created on my IBM account but in later steps go script throw and error:
`panic: interface conversion: interface {} is nil, not string`
Full logs in attachments.
[error.txt](https://github.com/IBM/packer-plugin-ibmcloud/files/6960744/error.txt)
[error-ansible.txt](https://github.com/IBM/packer-plugin-ibmcloud/files/6960745/error-ansible.txt)

I'm not sure if this is a bug or something is missing in my setup.

**Comment by juanpinzon** [comment]
I @jowko I think the reason is due the image you are using is deprecated. You can run `ibmcloud is images | grep centos` to find new available images as the Documentation https://github.com/IBM/packer-plugin-ibmcloud#source-block-in-detail stated. Here are two available images for centOS
```
r006-13938c0a-89e4-4370-b59b-55cd1402562d   ibm-centos-7-9-minimal-amd64-3
r006-de4fc543-2ce1-47de-b0b8-b98556a741da   ibm-centos-8-3-minimal-amd64-3 
```

**Comment by jowko** [comment]
There is some weird thing happening. I retrieved the newest 7.X Centos image: `r010-28e8b4ba-6ab7-4af8-a01c-d9c38ccb3203` which is named `ibm-centos-7-9-minimal-amd64-3`.

On git bash using docker image, I still have this issue.
I managed to install these binaries using packer init on Ubuntu 20.04.1 LTS (WSL2 on Windows 10).
Packer version: 1.7.4

When I run `build.vpc.centos.pkr.hcl` script, weird errors about ssh keys were printed. 
[ubuntu-no-env.txt](https://github.com/IBM/packer-plugin-ibmcloud/files/6966921/ubuntu-no-env.txt)
There are printed even when I comment variables referencing ssh keys (they are not used in this example anyway).
`==> ibmcloud-vpc.centos: [ERROR] Error reading SSH Public Key. Error: open : no such file or directory`
`==> ibmcloud-vpc.centos: [ERROR] Error creating the SSH Key for VPC [ERROR] Error reading SSH Public Key. Error: open : no such file or directory`

When I added environment variables referenced in manual installation section: https://github.com/IBM/packer-plugin-ibmcloud#manual-installation
There is no error about ssh keys but old issue still exists: `panic: interface conversion: interface {} is nil, not string`
[ubuntu-env.txt](https://github.com/IBM/packer-plugin-ibmcloud/files/6966944/ubuntu-env.txt)
Also, the weird thing is that I provided my own ssh key and packer still creates ssh key in IBM Cloud which is visible in logs.
After build is completed, ssh keys created by packer are not removed - should they be removed since no instance is left after build?

**Comment by juanpinzon** [comment]
Hi @jowko the newest 7.X Centos image available on IBM Cloud use `$ ibmcloud is images | grep centos | grep available` to get the correct image id.
```
$ ibmcloud is images | grep centos | grep available
r006-13938c0a-89e4-4370-b59b-55cd1402562d   ibm-centos-7-9-minimal-amd64-3                     available    amd64   centos-7-amd64                       7.x - Minimal Install                     1               public       provider     none         -   
r006-de4fc543-2ce1-47de-b0b8-b98556a741da   ibm-centos-8-3-minimal-amd64-3                     available    amd64   centos-8-amd64                       8.x - Minimal Install                     1               public       provider     none         -   
```
The SSH issue was due packer plugin requires to know the location of the SSH keys. You correctly solved the issue creating the `.env` file with the Environment Variables in there. They ssh keys created are removed at the end you can see the logs `Restoring local Private Key to a file /root/.ssh/id_rsa` and `Restoring local Public Key to a file /root/.ssh/id_rsa.pub`

About the `panic: interface conversion: interface {} is nil, not string` issue I am not able to replicate it neither on Ubuntu nor macOS. Could you please try to use a Linux or macOS machine instead of a Windows one and see if you still get the same error. 

Thanks

**Comment by jowko** [comment]
@juanpinzon I used the newest image for Centos:
```
$ ibmcloud is images | grep centos | grep available
r010-28e8b4ba-6ab7-4af8-a01c-d9c38ccb3203   ibm-centos-7-9-minimal-amd64-3                     available    amd64   centos-7-amd64                       7.x - Minimal Install                     1               public       provider     none         -
r010-3bef996a-0dd4-48cc-b857-fd03e8dfa0db   ibm-centos-8-3-minimal-amd64-3                     available    amd64   centos-8-amd64                       8.x - Minimal Install                     1               public       provider     none
```
I work in `eu-de` region, so I guess that this is the reason why I have different image id than you.
When I was writing about ssh keys, I meant keys which are generated and saved in IBM Cloud (VPC -> Compute -> SSH Keys).
See: 
![ssh-keys](https://user-images.githubusercontent.com/20277750/129153930-537b31b3-0d16-422f-9f49-318d29c9fc12.png)
I see that in the logs they are lines, like `Deleting SSH key for VPC packer-vpc-ssh-key-92530` but such key is not removed.

During these tests, I used Ubuntu installed on Windows WSL2. I also tried to use ibm-centos-8-3-minimal-amd64-3 but the result is the same.
I analyzed the go code and I suspect that the issue may be related to access rights for managing SG. I cannot confirm that now because I don't have necessary access rights in IBM Cloud to manage IAM (I can verify it after a few days).
But the logs says:
```
==> ibmcloud-vpc.centos: Creating a temp Security Group on VPC <VPC_ID> ...
==> ibmcloud-vpc.centos: Releasing the Floating IP: <IP> ...
```
And later:
```
panic: interface conversion: interface {} is nil, not string
...
/root/go/src/github.com/IBM/packer-plugin-ibmcloud/builder/ibmcloud/vpc/step_create_sec_group_rules.go:42
```
If SG would be handled correctly, there would be more logs related to SG but instead plugin removes immediately all resources.
Definitely error handling and logging could be improved. I'm not sure if there are more issues in that code but I will check it next week.

**Comment by jowko** [comment]
@juanpinzon Also, if you check `step_create_ssh_key_vpc.go`, there should be two logs instead of one in case of ssh key removal.
I had only: `Deleting SSH key for VPC packer-vpc-ssh-key-95344 ...`.
But according to code I should also have one of these lines too:
`[ERROR] Error deleting SSH key for VPC %s. Please delete it manually: %s`
`The Key was successfully deleted!`
So probably no error was returned by the client but results was different than 204 code.

Previous error logs were copied from the console.
I realized just now, that also crash.log is generated, which contains more information.
```
ui: [1;32m==> ibmcloud-vpc.centos: Creating a temp Security Group on VPC <VPC_ID> ...[0m
 packer-plugin-ibmcloud_v2.0.1_x5.0_linux_amd64 plugin: 2021/08/12 10:28:27 Response Status -  403
packer-plugin-ibmcloud_v2.0.1_x5.0_linux_amd64 plugin: 2021/08/12 10:28:27 Response Body from ibmcloud-  {"errors":[{"code":"not_authorized","message":"the provided token is not authorized to create security-groups in this account"}],"trace":"<HIDDEN_TRACE>"}
```
I think that error handling should be improved because these errors are not properly discovered by go code (`if err != nil`).
There are no additional logs for ssh key deletion.

**Comment by juanpinzon** [comment]
Hi @jowko thank you for catching the Deleting SSH key for VPC bug. I will take a look on what is going on and fix it. I will update the plugin as soon as I have a solid solution.
Likewise, thank you for pointing out about the error handling. I will review them to have a better control of them as well as a better trace of any error reported on the log.

In the meantime you can provide the security group identifier to use. Recall each VPC has a default security group you can use.

**Comment by juanpinzon** [comment]
Hi @jowko there is a `packerlog` folder with `packerlog.txt` file, could you please share it to me. Thanks

**Comment by juanpinzon** [comment]
Hi @jowko, I worked on your `Deleting SSH key for VPC` bug and seems the reason is due when a problem occurs running the plugin, like in your case, VPC does not have enough time to complete the provisioning of the Key, so when the plugin attempts to delete it, there is no Key. As a result, even thought there is no error, the Key eventually is created an left in the VPC Keys.

I already fixed the problem given some time to complete the provisioning of the Key when it is being provisioned. 
On file `step_create_ssh_key_vpc.go`. 
Find line `// Wait half minute before deleting SSH key - otherwise wouldn't be deleted.`
Uncomment line below `time.Sleep(30 * time.Second)`

Likewise, I added another check whit the API call return
```
if result == "204 No Content" {
	ui.Say("The Key was successfully deleted!")
} else {
	ui.Say("The key could not be deleted. Please delete it manually!")
}
```
I run 5 test and all of them deleted the Key on VPC. Could you please try in your end and let me know if It fixed the problem.

Best regards,
Juan

**Comment by jowko** [comment]
Hi @juanpinzon. It solved the problem in my case
