### ISSUE TITLE
SSH key handling issues

### ISSUE THREAD

**Issue by jowko** [IBM/packer-plugin-ibmcloud#38]
@juanpinzon There are weird cases in `step_create_ssh_key_pair.go` script.
`PRIVATE_KEY` and `PUBLIC_KEY` environment variables are read. If they are not set, error will be thrown by packer plugin:
```
==> ibmcloud-vpc.centos: [ERROR] Error reading SSH Public Key. Error: open : no such file or directory
==> ibmcloud-vpc.centos: [ERROR] Error creating the SSH Key for VPC [ERROR] Error reading SSH Public Key. Error: open : no such file or directory
```
I'm forced to set these environment variables and they need to point to existing files.
Otherwise I get such message:
```
==> ibmcloud-vpc.centos: Saving current SSH Private Key /root/.ssh/id_rsa
==> ibmcloud-vpc.centos: [ERROR] Error saving current SSH Private Key: open /root/.ssh/id_rsa: no such file or directory
```
Also, log messages are misleading, because on this step we do not save keys but read them (lines 28-53).
So I need to create any files and pass path to them in these environment variables.
Then packer works, even if these files are empty.
Also, plugin generates own key and saves it to these files. After work is finished, it restores the old version of these files.
I don't understand why this process looks in such way.
Shouldn't it work in such a way, that packer generates it's own key files and use them without overriding existing files?
Also, isn't current process risky? What if some unexpected error occur and existing keys will not be restored?

**Comment by juanpinzon** [comment]
This behavior is something expected and we are aware of it. 
On IBM infra, Ansible access SSH keys for communication at location
```
export PRIVATE_KEY="$HOME/.ssh/id_rsa"
export PUBLIC_KEY="$HOME/.ssh/id_rsa.pub"
```
That is the reason you need to state key's location on the `.env` file.

About your concern "Shouldn't it work in such a way, that packer generates it's own key files and use them without overriding existing files?" 
There are two reason for not doing this way:
- First one is that Ansible is going to look to above key's location on IBM infra. We cannot change it.
- The second one is due we cannot change the location of the SSH Keys, when packer generate new ones will override your local keys, so you will loose them. 
My advise to you is to make a copy of your current SSH keys in another folder.

**Comment by jowko** [comment]
Something is not right.
I set such values:
export PRIVATE_KEY="id_rsa"
export PUBLIC_KEY="id_rsa.pub"
And created empty files with such names in the same directory when packer build was run.
When I run Packer, Ansible is run with such command:
```
ansible-playbook -e packer_build_name="centos" -e packer_builder_type=ibmcloud-vpc --ssh-extra-args '-o IdentitiesOnly=yes' -e ansible_ssh_private_key_file=/tmp/ansible-key069239334 -i /tmp/packer-provisioner-ansible132910925 /home/jenkins/.../playbook.yml
```
And it works (except build failure after 60 minutes described in #39).
Ansible doc suggest that passed key is autogenerated: https://www.packer.io/docs/provisioners/ansible/ansible#ssh_authorized_key_file

Ansible uses `PRIVATE_KEY` and `PUBLIC_KEY` environment variables internally? Documentation doesn't suggest such thing.

**Comment by juanpinzon** [comment]
Hi @jowko I already told you, in my last comment, that on IBM infra Ansible works differently and explained to you how to run it and pointed you to an example. You can try to set environment variables  for Anisble, but it wouldn't work.
