### ISSUE TITLE
Build the plugin errors

### ISSUE THREAD

**Issue by bgawryluik** [IBM/packer-plugin-ibmcloud#4]
Tried to run go build based off the latest version of the README (2020-02-07) and I get the following errors:

```
go build

main.go:7:2: cannot find package "github.com/ibmcloud/packer-builder-ibmcloud/builder/ibmcloud" in any of:
	/usr/local/go/src/github.com/ibmcloud/packer-builder-ibmcloud/builder/ibmcloud (from $GOROOT)
	/home/vagrant/go/src/github.com/ibmcloud/packer-builder-ibmcloud/builder/ibmcloud (from $GOPATH)
main.go:8:2: cannot find package "github.com/ibmcloud/packer-builder-ibmcloud/version" in any of:
	/usr/local/go/src/github.com/ibmcloud/packer-builder-ibmcloud/version (from $GOROOT)
	/home/vagrant/go/src/github.com/ibmcloud/packer-builder-ibmcloud/version (from $GOPATH)
```

Also I couldn't clone this repo unless I changed the clone command from SSH to HTTPS:
```
git clone https://github.com/IBM/packer-plugin-ibmcloud.git
```

And finally, this command should be changed from:
```
cd $GOPATH/src/github.com/ibmcloud/packer-builder-ibmcloud
```
to 
```
cd $GOPATH/src/github.com/ibmcloud/packer-plugin-ibmcloud
```

Thanks very much for your previous EXTREMELY QUICK response to the original issues!

**Comment by indirakalagara** [comment]
I too had the above issue and after following above step, I still have the issue with go build as below

go build
# github.com/ibmcloud/packer-plugin-ibmcloud
./main.go:17:28: cannot use new(ibmcloud.Builder) (type *ibmcloud.Builder) as type packer.Builder in argument to server.RegisterBuilder:
	*ibmcloud.Builder does not implement packer.Builder (missing ConfigSpec method)

**Comment by williamsjasonj** [comment]
I don't see any updates on this, and this issue still exists.  I am assuming this project is no longer maintained?

**Comment by Nitinhuralikuppi** [comment]
Issue addressed on latest commit.
