### ISSUE TITLE
Ubuntu 22.04 container env Ansible provisioner fails; it seems ssh rsa won't be supported in the combination of Ubuntu 22.04 and Ansible provisioner

### ISSUE THREAD

**Issue by syyang-in-cloud** [IBM/packer-plugin-ibmcloud#46]
**Describe the bug**
Tried to run the latest packer plugin v3.0.0 under ubuntu 22.04 docker container, and got the failure with the ansible provisioner

**To Reproduce**
run packer plugin with ansible provisioner under ubuntu 22.04

**Expected behavior**
Ansible provisioner should not fail; Since Packer plugin creates SSH key, there should be some workaround in Packer Plugin or Ansible provisioner.

**Screenshots**
```
│     ibmcloud-vpc.ubuntu-focal: TASK [Gathering Facts] *********************************************************
│ ==> ibmcloud-vpc.ubuntu-focal: failed to handshake
│     ibmcloud-vpc.ubuntu-focal: fatal: [default]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Unable to negotiate with 127.0.0.1 port 40097: no matching host key type found. Their offer: ssh-rsa", "unreachable": true}
│     ibmcloud-vpc.ubuntu-focal:
```

**Comment by syyang-in-cloud** [comment]
Please refer the AskUbuntu Q&A: https://askubuntu.com/questions/1409105/ubuntu-22-04-ssh-the-rsa-key-isnt-working-since-upgrading-from-20-04

There seems some workarounds ...

**Comment by syyang-in-cloud** [comment]
could workaround packer template for Ansible provisioner as mentioned in https://github.com/hashicorp/packer-plugin-ansible/issues/6#issuecomment-1044515290 :
```
  provisioner "ansible" {
    playbook_file = var.ansible_file
    ansible_env_vars = [
      "ANSIBLE_SSH_ARGS='-oHostKeyAlgorithms=+ssh-rsa -oPubkeyAcceptedKeyTypes=ssh-rsa'",
      "ANSIBLE_HOST_KEY_CHECKING=False"
    ]
  }
```

**Comment by syyang-in-cloud** [comment]
Another workaround can be adding the last two lines for the global ssh_config 
```
ubuntu@d469a0e5c748:/iaas-tfp/02-packer-ubuntu-22.04$ cat /etc/ssh/ssh_config

# This is the ssh client system-wide configuration file.  See
# ssh_config(5) for more information.  This file provides defaults for
# users, and the values can be changed in per-user configuration files
# or on the command line.

# Configuration data is parsed as follows:
#  1. command line options
#  2. user-specific file
#  3. system-wide file
# Any configuration value is only changed the first time it is set.
# Thus, host-specific definitions should be at the beginning of the
# configuration file, and defaults at the end.

# Site-wide defaults for some commonly used options.  For a comprehensive
# list of available options, their meanings and defaults, please see the
# ssh_config(5) man page.

Include /etc/ssh/ssh_config.d/*.conf

Host *
.
.
.
    PubkeyAcceptedKeyTypes +ssh-rsa
    HostKeyAlgorithms +ssh-rsa
```

**Comment by syyang-in-cloud** [comment]
It seems the issue can be seen only when the packer is running from a docker container ... if the packer is running from a VM, then it seems fine. I suspect there's something extra config to allow rsa key in sshd config.

**Comment by syyang-in-cloud** [comment]
I guess that the similar issue should have been observed in Fedora since they removed rsa option earlier... 
It seems Hashicorp updated to support multiple option of ssh key type and bits : https://pkg.go.dev/github.com/hashicorp/packer-plugin-sdk/communicator#SSHTemporaryKeyPair

**Comment by syyang-in-cloud** [comment]
An informative thread : https://github.com/hashicorp/packer/issues/11733
AWS, GCP, and the other competitors have plugin level workaround: https://github.com/hashicorp/packer/issues/11733#issuecomment-1106564658
```
"temporary_key_pair_type": "ed25519",
```

Otherwise we have to enable `ssh rsa` globally.

**Comment by KarstenB** [comment]
The same error can also be produced on Mac. Took me a while to understand that the error needs to be fixed on the Mac side, not the image that is to be build.
I used the solution to add:
```
Host *
    PubkeyAcceptedKeyTypes +ssh-rsa
    HostKeyAlgorithms +ssh-rsa
```
to my local `~/.ssh/config` file.

**Comment by BShrivastav** [comment]
Works with ubuntu 22.4 along with an ansible provisioner is working fine. 
@syyang-in-cloud, Could you comment if we still getting into this ?

**Comment by syyang-in-cloud** [comment]
@BShrivastav , we will still get the issue until IBMCLOUD supports multiple key types. I would like to keep this issue open until then, so that people from public can add the workaround and realize when they can remove that. 
Thanks!

**Comment by syyang-in-cloud** [comment]
> @BShrivastav , we will still get the issue until IBMCLOUD supports multiple key types. I would like to keep this issue open until then, so that people from public can add the workaround and realize when they can remove that.
> Thanks!

@BShrivastav , we will still get the issue until IBMCLOUD supports multiple key types. I would like to keep this issue open until then, so that people from public can add the workaround and realize when they can remove that.
Thanks!

**Comment by syyang-in-cloud** [comment]
> Works with ubuntu 22.4 along with an ansible provisioner is working fine. @syyang-in-cloud, Could you comment if we still getting into this ?

@BShrivastav , we will still get the issue until IBMCLOUD supports multiple key types. I would like to keep this issue open until then, so that people from public can add the workaround and realize when they can remove that.
Thanks!
