### ISSUE TITLE
Feature Request: parallel packer build

### ISSUE THREAD

**Issue by syyang-in-cloud** [IBM/packer-plugin-ibmcloud#47]
**Is your feature request related to a problem? Please describe.**
parallel image build

**Describe the solution you'd like**
build {
  sources = [
    "source.ibmcloud-vpc.ubuntu-focal",
    "source.ibmcloud-vpc.ubuntu-jammy"
  ]
.
.
}

**Describe alternatives you've considered**
sequential build as of now

**Additional context**

packer  parallel build seems not working, maybe I can request as a feature in github later, For example:
```
build {
  sources = [
    "source.ibmcloud-vpc.ubuntu-focal",
    "source.ibmcloud-vpc.ubuntu-jammy"
  ]
.
.
}
```
The packer plugin creates the same directory for both ssh key, and one of the build instance fails as below, then the failed instance delete the ssh key pair folder/files:
```
==> Some builds didn't complete successfully and had errors:
--> ibmcloud-vpc.ubuntu-jammy: Packer experienced an authentication error
when trying to connect via SSH. This can happen if your username/password are
wrong. You may want to double-check your credentials as part of your
debugging process. original error: ssh: handshake failed: ssh: unable to
authenticate, attempted methods [none publickey], no supported methods remain

==> Builds finished. The artifacts of successful builds are:
--> ibmcloud-vpc.ubuntu-focal: Image Name: ubuntu-0-1-0-ba54-focal || Image
ID: r006-5f4592f3-3032-4d44-a035-c83b356645d6
```

**Comment by juanpinzon** [comment]
Issue was solved on v3.0.1
