### ISSUE TITLE
Better docs in terraform plugin location

### ISSUE THREAD

**Issue by powellquiring** [IBM/packer-plugin-ibmcloud#51]
**Describe the bug**

Publish plugin to: https://www.terraform.io/plugin and add/fix the following info to the docs:

- [ ] Later option requires you run packer plugin inside your VPC.  Change to:  Private requires access to the private IP address of the instance.
- [ ] vpc_endpoint_url - what is this?
- [ ] iam_url ?
- [ ] provide detailed IAM requirements, provide a terraform based IAM construction with the minimal IAM requirements
- [ ] timeouts should document the default value
- [ ] the default timeout value should be sufficient for %95 success
https://bigblue.aha.io/features/VPCIMG-143

**Comment by juanpinzon** [comment]
Hi Powell, sure I will let the VPC team know about this.

- Plugin can be run from any place, the only difference is user need to setup `vsi_interface`. Set it as "public" to create a Floating IP to connect to the temp VSI. Set it as "private" to use private interface to connect to the temp VSI. Later option requires you run packer plugin inside your VPC. Changing it to "Private requires access to the private IP address of the instance." is not correct due if you chose "private" you MUST run packer plugin from another VSI within the VPC,

- `timeout` MUST be customized by the user depending of the use case, aka the amount of software being installed on the VSI. There is no right answer, and the user should estimate the time base on it.

**Comment by powellquiring** [comment]
The private IP address can be accessed in a number of ways.  Here are some examples:
- Direct link
- VPN site to site
- VPN client to site
- Remote VPC through transit gateway

For timeout document the amount of timeout that would typically be required to handle a NO-OP packer configuration.  Makes sense for the user to add on the time to execute the packer code they provide.
