### ISSUE TITLE
Support for IBM Cloud Power Virtual Systems 

### ISSUE THREAD

**Issue by scentoni** [IBM/packer-plugin-ibmcloud#69]
We need an automated solution to build AIX and Linux images on https://cloud.ibm.com/power. Using Packer to do this would be an improvement over other automation methods, such as scripting individual `ibmcloud` CLI commands, REST API calls, or Terraform commands with Bash. It should support using the IBM stock image catalog, the workspace image catalog, and IBM Cloud Object Storage. It should support both AIX and Linux.

**Comment by BShrivastav** [comment]
Thanks for the inputs, We will evaluate this proposal and revert as sooner as possible.

**Comment by BShrivastav** [comment]
@scentoni, Could we connect to discuss on this sometimes ?
