### ISSUE TITLE
Instance UserData string configuration option

### ISSUE THREAD

**Issue by smathews** [IBM/packer-plugin-ibmcloud#70]
**Is your feature request related to a problem? Please describe.**

Currently the only option for userdata is `vsi_user_data_file`, which requires a file path containing userdata. This forces the use of a static userdata script.

**Describe the solution you'd like**

Add a new configuration variable `vsi_user_data` for string userdata input, allowing dynamic userdata when using the packer function `templatefile`.

**Describe alternatives you've considered**

Running an initialization script before running packer to generate the userdata:
  - Not generic enough
  - Would not have access to packer variables

Create a custom data source:
  - Fair amount of custom code and implementation to avoid an option that should be part of the base plugin
  - Default behavior of the API is being overridden by the file path "helper" configuration variable `

**Additional context**

[See use of `templatefile`](https://www.hashicorp.com/blog/using-template-files-with-hashicorp-packer)

**Comment by BShrivastav** [comment]
Thanks, We will soon be supporting this feature request, wip.
