### ISSUE TITLE
Optional Reboot

### ISSUE THREAD

**Issue by smathews** [IBM/packer-plugin-ibmcloud#79]
**Is your feature request related to a problem? Please describe.**
Having a reboot at the end of the build makes it difficult (impossible) to run sysprep after software install and have a clean instance. This requires us to take the image created from the plugin, create a new vsi, run sysprep, and then image that new vsi. 

**Describe the solution you'd like**
Add a new option (default to true for backwards compatibility) for running the reboot step. Also, please account for the instance possibly being off when the capture image step is run.

**Describe alternatives you've considered**
Reimage after the packer image is created and run sysprep outside packer, this incurs >2x the prep time.

**Comment by BShrivastav** [comment]
Hi @smathews,

Thanks for reaching us out with the suggestion, will evaluate and update you sooner on this.
