### ISSUE TITLE
vsi_boot_vol_capacity is an Unsupported Argument

### ISSUE THREAD

**Issue by justin-vanwinkle** [IBM/packer-plugin-ibmcloud#92]
**Describe the bug**
I'm unable to set the volume size with `vsi_boot_vol_capacity`. Packer complains that it is an "Unsupported Argument"

**Comment by astha-jain** [comment]
We are making the release very soon. Once you try it you should be able to use the attribute.

**Comment by astha-jain** [comment]
New release is available https://github.com/IBM/packer-plugin-ibmcloud/releases/tag/v3.2.2
