### ISSUE TITLE
Release v3.2.0 is broken

### ISSUE THREAD

**Issue by jvidalallende** [IBM/packer-plugin-ibmcloud#94]
**Describe the bug**
Release v3.2.0 of the plugin is broken, and packer cannot download the artifacts.
Checksums are missing, and apparently the names of the files are not correct, or at least they don't follow the same convention as earlier releases.

Packer shows this error when trying to get the last version of the plugin:
```
could not get sha256 checksum file for github.com/ibm/ibmcloud version 3.2.0. Is the file present on the release and correctly named ? GET https://github.com/ibm/packer-plugin-ibmcloud/releases/download/v3.2.0/packer-plugin-ibmcloud_v3.2.0_SHA256SUMS: 404  []
```

**To Reproduce**
Run a packer build that has no pinned dependency for the plugin version, for example:
```
packer { 
  required_plugins { 
    # https://github.com/IBM/packer-plugin-ibmcloud
    ibmcloud = {
      source = "github.com/IBM/ibmcloud"
      version >= "v3.0.2"
    } 
  } 
} 
```

**Expected behavior**
Packer should be able to seamlessly install v3.2.0.

**Screenshots**
Here is the difference in naming and number of artifacts between v3.1.1, which works OK, and v3.2.0:
![Screenshot from 2023-08-31 13-24-07](https://github.com/IBM/packer-plugin-ibmcloud/assets/1612830/a0b4adae-6514-4610-8d9d-9dd10cb6d9c7)

**Comment by astha-jain** [comment]
Fixed https://github.com/IBM/packer-plugin-ibmcloud/releases/tag/v3.2.2
