### ISSUE TITLE
Missing documentation for 'classic' builder

### ISSUE THREAD

**Issue by oaksofmamre** [IBM/packer-plugin-ibmcloud#96]
**Describe the bug**
It is not clear what the purpose of this is: 
https://github.com/IBM/packer-plugin-ibmcloud/tree/master#builders
Click "classic"

**To Reproduce**
1. Go to https://github.com/IBM/packer-plugin-ibmcloud/tree/master#builders
2. Click on 'classic'
3. See error 404

**Expected behavior**
Expect to see documentation (of required and optional values, for example) on how to use classic.

**Comment by astha-jain** [comment]
Doc links fixed
